import { JobCompetencyMap } from './JobCompetencyMap';
import { GenerationModeSwitch } from '../components/GenerationModeSwitch';
import { useState } from 'react';
import { Modal } from '../components/Modal';
import { Icon } from '../components/Icon';
import { catalog, sampleContext, gate, draftRole, defaultDesign, taskTypes, designError, generateProject } from './model.mjs';
import './generation.css';
const steps=['课程关联','岗位与任务','教学化转化','审阅项目'];
const readContext=()=>{try{return JSON.parse(localStorage.getItem('ai-course-context-v1'))||{};}catch{return {};}};
export function LearningBrief({design,title,showGraph=true}){
 return <div className="learning-brief"><div className="learning-heading"><span className="gen-tag">学习型工作任务</span><strong>{design.role.name}</strong><span>{design.hours} 课时 · 教学草稿</span></div><p><b>核心问题</b>{design.problem}</p><div className="learning-grid"><p><b>学情与先备条件</b>{design.learners}；{design.prerequisites}</p><p><b>项目成果</b>{design.product}</p></div>{showGraph&&<JobCompetencyMap key={`${design.role.id}-${design.sourceTask?.id}`} design={design} title={title}/>}<details className="learning-provenance"><summary>查看来源与教学设计</summary><div className="learning-provenance-body"><div className="learning-grid">{[['任务类型',design.taskType||'综合型'],['课程学习目标',design.courseGoal],['工作任务',design.sourceTask.title],['工作对象',design.object],['工作内容',design.content],['工具与资源',design.tools],['组织方式',design.organization],['学习环境',design.environment],['学习支持',design.scaffold],['验收标准',design.criteria],['迁移挑战',design.transfer]].map(([name,value])=><p key={name}><b>{name}</b>{value}</p>)}</div><p className="gen-source">{design.role.origin==='reference'?`${design.role.source.school} · ${design.role.source.file} · ${design.role.source.locator}；来源岗位：${design.role.originalRole}`:'教师输入岗位 · 本地辅助草稿，需补充岗位调研证据'}</p><p className="gen-source">{design.review}。教学设计由本地规则转化，非在线 AI 结果。</p></div></details></div>;
}
export function ActivityBrief({activity}){return <div className="activity-brief"><p><b>引导问题</b>{activity.question}</p><p><b>提交成果</b>{activity.evidence}</p><p><b>评价依据</b>{activity.criteria}</p><p><b>学习支持</b>{activity.support}</p></div>;}
export function GenerationWizard({onClose,onCreate,onModeChange}){
 const [step,setStep]=useState(0),[context,setContext]=useState(readContext),[role,setRole]=useState(null),[task,setTask]=useState(null),[selected,setSelected]=useState([]),[query,setQuery]=useState(''),[manual,setManual]=useState(false),[name,setName]=useState(''),[work,setWork]=useState(''),[design,setDesign]=useState(null),[review,setReview]=useState(false),[error,setError]=useState('');
 const status=gate(context), roles=status.ready?catalog.filter(r=>(!context.major||r.major===context.major)&&(!context.planId||r.planId===context.planId)&&r.name.includes(query.trim())):[];
 const abilities=task?.abilities.filter(a=>selected.includes(a.id))||[];
 const changeContext=c=>{setContext(c);setRole(null);setTask(null);setSelected([]);setDesign(null);setReview(false);setError('');};
 const pick=(r,t=r.tasks[0])=>{setRole(r);setTask(t);setSelected(t.abilities.map(a=>a.id));setDesign(null);setReview(false);setError('');};
 const patch=(key,value)=>{setDesign(d=>({...d,[key]:value}));setReview(false);};
 const next=()=>{setError('');if(step===0){if(!status.ready)return setError('人培专业与课程专业不一致，请重新选择或清空');try{localStorage.setItem('ai-course-context-v1',JSON.stringify(context));}catch{}setStep(1);}else if(step===1){if(!role||!task||!abilities.length)return setError('请选择工作任务及至少一项岗位能力');if(abilities.some(a=>!a.title.trim()))return setError('请补全已选能力的描述');setDesign(d=>d||defaultDesign(role,task));setStep(2);}else if(step===2){const msg=designError(design);if(msg)return setError(msg);setStep(3);}else{try{onCreate(generateProject({context,role,task,abilities,design,confirmed:review}));}catch(e){setError(e.message);}}};
 let preview=null;if(step===3){try{preview=generateProject({context,role,task,abilities,design,confirmed:true});preview.learningDesign.review='自动转化预览，尚待教师确认';}catch{}}
 return <Modal title="从岗位工作任务生成学习项目" wide className="generation-modal" onClose={onClose} footer={<>{step===3&&<span className="gen-footer-note">生成后保存为新项目，可继续编辑</span>}<button className="outlined" onClick={()=>step? (setStep(step-1),setError(''),setReview(false)):onClose()}>{step?'上一步':'取消'}</button><button className="primary" disabled={(step===0&&!status.ready)||(step===3&&!review)} onClick={next}>{step===3?'确认并创建项目':step===2?'生成转化预览':'下一步'}<Icon name={step===3?'check':'arrow'} size={16}/></button></>}>
 <GenerationModeSwitch enabled onChange={onModeChange}/>
 <div className="gen-stepper">{steps.map((s,i)=><div key={s} className={i===step?'current':i<step?'done':''}><span>{i<step?'✓':`0${i+1}`}</span>{s}</div>)}</div>
 <div className="gen-workspace">
 <aside className="gen-guide"><span className="gen-tag">岗位 → 学习项目</span><h3>让工作任务<br/>成为学习的起点</h3><p>保留真实工作的逻辑，以问题组织学习，以成果检验能力。</p><div className="gen-route"><span>典型工作任务</span><i>↓ 教学性改造</i><span>学习型工作任务</span><i>↓ 项目承载</i><span>阶段 · 活动 · 评价</span></div></aside>
 <section className="gen-main">
 {step===0&&<><div className="gen-section-title"><div><h3>关联课程信息（选填）</h3><p>可关联专业和人培方案筛选参考岗位，也可直接下一步选择岗位或手动补充。</p></div><span className={`gen-status ${status.ready?'ready':''}`}>{status.ready?'可继续':'请调整关联'}</span></div><div className="gen-checks">{status.checks.map((s,i)=><div key={s.name}><span className={s.ok?'passed':''}>{s.ok?'✓':'—'}</span><div><strong>{s.name}</strong><p>{s.detail}</p></div></div>)}</div><div className="gen-notice">专业和人培方案均为选填，留空不影响生成项目。参考岗位保留人培出处，请结合教学需要选择。</div><div className="gen-form-grid"><label>关联专业（选填）<select value={context.major||''} onChange={e=>changeContext({major:e.target.value,majorName:e.target.value?'工业机器人技术':''})}><option value="">暂不关联专业</option><option value="460305">460305 · 工业机器人技术</option></select></label><label>人培方案（选填）<select value={context.planId||''} onChange={e=>changeContext({...context,planId:e.target.value,planMajor:e.target.value?'460305':'',planName:e.target.value?(e.target.value==='xc-2025'?sampleContext.planName:'本校人培（本地配置）'):''})}><option value="">尚未关联人培</option><option value="xc-2025">许昌职业技术学院 · 2025级（参考样本）</option><option value="local-plan">本校人培（暂无岗位样本）</option></select></label></div><button className="outlined" onClick={()=>changeContext({...sampleContext})}><Icon name="stack" size={16}/>载入示例关联</button></>}
 {step===1&&<><div className="gen-section-title"><div><h3>选择岗位的典型工作任务</h3><p>本次从选定任务生成一个学习情境项目，保留能力与出处。</p></div></div><div className="gen-mode"><button className={!manual?'active':''} onClick={()=>{setManual(false);setRole(null);setTask(null);setSelected([]);setDesign(null);}}>从参考岗位选择</button><button className={manual?'active':''} onClick={()=>{setManual(true);setRole(null);setTask(null);setSelected([]);setDesign(null);}}>未找到合适岗位，手动补充</button></div>{!manual?<><input aria-label="搜索岗位" className="gen-search" placeholder="搜索参考岗位" value={query} onChange={e=>setQuery(e.target.value)}/><div className="gen-role-list">{roles.map(r=><button className={role?.id===r.id?'selected':''} key={r.id} onClick={()=>pick(r)}><Icon name="users"/><strong>{r.name}</strong><small>{r.tasks.length} 个工作任务 · 人培参考</small></button>)}{!roles.length&&<div className="gen-empty"><strong>没有找到相应岗位</strong><p>可换一个关键词，或手动补充岗位及主要工作。</p><button className="outlined" onClick={()=>{setManual(true);setRole(null);setTask(null);setDesign(null);}}>手动补充岗位</button></div>}</div></>:<div className="gen-manual"><div className="gen-notice">AI 生成接口尚未接入。可先基于岗位和主要工作生成本地辅助草稿，编辑确认后再转化为项目。</div><div className="gen-form-grid"><label>岗位名称<input value={name} placeholder="如：工业视觉质检员" onChange={e=>{setName(e.target.value);setRole(null);setTask(null);setDesign(null);}}/></label><label>主要工作 / 典型任务<input value={work} placeholder="如：完成零件表面缺陷检测与报告" onChange={e=>{setWork(e.target.value);setRole(null);setTask(null);setDesign(null);}}/></label></div><button className="primary" onClick={()=>{try{pick(draftRole(context,name,work));}catch(e){setError(e.message);}}}><Icon name="sparkle" size={16}/>生成任务与能力草稿</button></div>}
 {task&&<div className="gen-task-source"><div className="gen-section-title"><h4>{task.title}</h4><span className="gen-tag">{role.origin==='reference'?'人培参考 · 待复核':'辅助草稿 · 可编辑'}</span></div><p className="gen-source">{role.origin==='reference'?`${role.source.school} · ${role.source.file} · ${role.source.locator}。来源岗位：${role.originalRole}。当前名称为历史匹配结果。`:role.source.note}</p>{['知识','技能','素养'].map(c=><div key={c} className="gen-abilities"><h4>{c}<small>{task.abilities.filter(a=>a.category===c).length} 项</small></h4>{task.abilities.filter(a=>a.category===c).map(a=><label className="gen-ability" key={a.id}><input type="checkbox" checked={selected.includes(a.id)} onChange={e=>{setSelected(ids=>e.target.checked?[...ids,a.id]:ids.filter(x=>x!==a.id));setReview(false);}}/>{role.origin==='reference'?<span>{a.title}<small>{a.id} · {a.locator}</small></span>:<input aria-label={`${c}能力草稿`} value={a.title} onChange={e=>{const updated={...task,abilities:task.abilities.map(x=>x.id===a.id?{...x,title:e.target.value}:x)};setTask(updated);setRole({...role,tasks:[updated]});setReview(false);}}/>}</label>)}{!task.abilities.some(a=>a.category===c)&&<p className="gen-source">来源未提供独立{c}项；教学设计可补充育人目标，不能标作人培原文。</p>}</div>)}<div className="gen-selection">已选 {abilities.length} 项能力 · 将关联到学习活动与评价</div></div>}</>}
 {step===2&&design&&<><div className="gen-section-title"><div><h3>把岗位要求转化为可学习的任务</h3><p>已自动填入教学草稿，请结合本班学情和实训条件调整。</p></div></div><div className="gen-conversion"><span>{task.title}</span><Icon name="arrow"/><strong>学习情境 + 核心问题 + 可评价成果</strong></div><div className="gen-form-grid"><label className="span-2">项目名称<input value={design.title} onChange={e=>patch('title',e.target.value)}/></label><label>学习任务类型<select value={design.taskType} onChange={e=>{setDesign(d=>({...d,taskType:e.target.value,...taskTypes[e.target.value]}));setReview(false);}}>{Object.keys(taskTypes).map(t=><option key={t}>{t}</option>)}</select></label><label>课程学习目标<input value={design.courseGoal} onChange={e=>patch('courseGoal',e.target.value)}/></label><label>学习者与学情<input value={design.learners} onChange={e=>patch('learners',e.target.value)}/></label><label>建议课时<input type="number" min="6" max="120" value={design.hours} onChange={e=>patch('hours',Number(e.target.value))}/></label><label className="span-2">先备知识与技能<input value={design.prerequisites} onChange={e=>patch('prerequisites',e.target.value)}/></label><label className="span-2">驱动学习的核心问题<textarea rows={2} value={design.problem} onChange={e=>patch('problem',e.target.value)}/></label></div><h4 className="gen-subtitle">重构工作六要素</h4><div className="gen-form-grid">{[['object','工作对象'],['content','工作内容'],['tools','工具、方法与资源'],['organization','组织与分工'],['product','产品 / 服务成果'],['environment','学习环境与实施条件']].map(([k,label])=><label key={k}>{label}<textarea rows={2} value={design[k]} onChange={e=>patch(k,e.target.value)}/></label>)}</div><h4 className="gen-subtitle">学习支持与评价</h4><div className="gen-form-grid">{[['scaffold','支持与难度调整'],['criteria','成果验收标准'],['transfer','迁移与挑战']].map(([k,label])=><label key={k} className={k==='transfer'?'span-2':''}>{label}<textarea rows={2} value={design[k]} onChange={e=>patch(k,e.target.value)}/></label>)}</div><div className="gen-notice">能力目标来自已选 {abilities.length} 项。按完整行动过程组织阶段；课时分配为建议，具体顺序与评价标准需结合岗位调整。</div></>}
 {step===3&&preview&&<><div className="gen-section-title"><div><h3>{preview.title}</h3><p>{preview.stages.length} 个阶段 · {abilities.length} 项能力 · {design.hours} 课时</p></div><span className="gen-tag">待教师确认</span></div><LearningBrief design={preview.learningDesign}/><div className="gen-preview-stages">{preview.stages.map((s,i)=><details key={s.id} open={i===0}><summary><span>0{i+1}</span><strong>{s.title}</strong><small>{s.hours} 课时</small></summary><h4>{s.tasks[0].title}</h4><ActivityBrief activity={s.tasks[0].learningActivity}/><p className="gen-source">关联能力：{s.tasks[0].learningActivity.abilityIds.map(a=>abilities.find(x=>x.id===a)?.title).join('；')||'过程性活动，按工作计划和质量要求评价'}</p></details>)}</div><div className="gen-review"><strong>教师审阅要点</strong><p>任务是否真实且有代表性？课时和设备是否可行？能力是否覆盖课程目标？难度、趣味性、跨领域协作和育人价值是否适合本班？</p><label className="checkbox"><input type="checkbox" checked={review} onChange={e=>setReview(e.target.checked)}/>我已审阅岗位来源与教学转化，确认创建可编辑的项目草稿</label></div></>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 </section></div></Modal>;
}
