import {migrateGeneratedKnowledgeLimit} from './generation/knowledge-matching.mjs';
import {initialConfig,readConfig,CONFIG_KEY,cmsHref} from './cms/config.mjs';
import {FrameworkDialog} from './generation/FrameworkDialog';
import { ContentAssociation } from './components/ContentAssociation';
import { courseResources, associateContents, resolveProjectContents } from './resources/model.mjs';
import { loadKnowledgeGraph } from './knowledge/model.mjs';
import { contentSources } from './components/TaskContentMenu';
import { useEffect, useState } from 'react';
import { GenerationWizard } from './generation/GenerationWizard';
import { KnowledgeGraph } from './knowledge/KnowledgeGraph';
import { Icon } from './components/Icon';
import { Modal } from './components/Modal';
import { ProjectActions } from './components/ProjectActions';
import { ProjectForm } from './components/ProjectForm';
import { ProjectEditor } from './components/ProjectEditor';
import { ProjectPreview } from './components/ProjectPreview';
import { appendTemplate, createProject, id, seedProject, validateProject } from './project.mjs';
const courseName='智能制造岗位项目课程';
const tabs=[['知识库','books'],['课程模型','graph'],['AI应用','sparkle'],['AI决策中心','chart']];
const groups=[{label:'知识模型',items:[['知识图谱','通过图的形式表达知识点关系','graph','blue']]},{label:'能力模型',items:[['能力图谱','基于课程目标建课程能力模型','pentagon','purple']]},{label:'问题模型',items:[['问题图谱','解决问题和决策时的关键工具','tree','cyan'],['问答对','提炼关键问题，补充特定知识','chats','cyan']]},{label:'素质模型',items:[['素质图谱','将抽象育人目标具象化','plant','orange']]}];
const descriptions={'知识库':'集中管理课程教材、教学课件与参考资料，为课程模型和 AI 应用提供知识来源。','AI应用':'围绕课程学习与项目实践，配置教学助手和学习工具。','AI决策中心':'连接课程目标、学习过程与项目成果，支持教学分析。','知识图谱':'梳理课程知识点及其关联关系，为项目任务关联学习内容。','能力图谱':'从课程目标出发，组织项目实践所需的能力及评价依据。','问题图谱':'以真实问题组织学习，连接问题、任务与知识。','问答对':'沉淀课程中的关键问题与回答，为学习提供及时支持。','素质图谱':'将素质目标关联到项目情境和具体实践任务。','增强知识库':'补充课程专属资料，为后续 AI 教学应用提供知识支持。','成员':'管理课程教师、助教与学习成员。'};
function readProjects(){try{const saved=JSON.parse(localStorage.getItem('ai-course-projects-v1'));if(Array.isArray(saved)&&saved.every(p=>typeof p.title==='string'&&Array.isArray(p.stages))){const migrated=saved.map(migrateGeneratedKnowledgeLimit);if(migrated.some((p,i)=>p!==saved[i])&&!localStorage.getItem('ai-course-projects-before-knowledge-limit-v1')){try{localStorage.setItem('ai-course-projects-before-knowledge-limit-v1',JSON.stringify(saved));}catch{return saved;}}return migrated;}}catch{}return [seedProject()];}
export function App(){
 const [cmsConfig,setCmsConfig]=useState(initialConfig);
 useEffect(()=>{const refresh=event=>{if(event?.type==='storage'&&event.key!==CONFIG_KEY)return;setCmsConfig(readConfig());};window.addEventListener('storage',refresh);window.addEventListener('course-config',refresh);return()=>{window.removeEventListener('storage',refresh);window.removeEventListener('course-config',refresh);};},[]);
 useEffect(()=>{setModal(previous=>previous?.type==='generate-job'?null:previous);},[cmsConfig]);
 const [previewId,setPreviewId]=useState(null);
 const [graph,setGraph]=useState(loadKnowledgeGraph);
 const [projects,setProjects]=useState(readProjects); const [activeId,updateActiveId]=useState(projects[0]?.id||null); const [tab,updateTab]=useState('课程模型');const [section,updateSection]=useState('project');const [collapsed,setCollapsed]=useState(false);const [modal,setModal]=useState(null);const [toast,setToast]=useState('');const [form,setForm]=useState({});const [error,setError]=useState('');
 const currentProject=projects.find(p=>p.id===activeId)||projects[0];
 const project=currentProject?resolveProjectContents(currentProject,graph,courseResources):null;
 useEffect(()=>{try{localStorage.setItem('ai-course-projects-v1',JSON.stringify(projects));}catch{setToast('浏览器无法保存草稿，请保持页面打开');}},[projects]);
 useEffect(()=>{if(toast){const timer=setTimeout(()=>setToast(''),3200);return()=>clearTimeout(timer);}},[toast]);
 // Reset preview in the navigation action, so initial effects cannot cancel an early click.
 const setActiveId=value=>{setPreviewId(null);updateActiveId(value);};
 const setTab=value=>{setPreviewId(null);updateTab(value);};
 const setSection=value=>{setPreviewId(null);updateSection(value);};
 const mutate=(fn,targetId=project?.id)=>setProjects(previous=>previous.map(p=>{if(p.id!==targetId)return p;const copy=structuredClone(p);fn(copy);if(copy.learningDesign){copy.learningDesign.review='教师编辑后的草稿；请核对目标、活动与评价一致性';}return copy;}));
 const open=m=>{if(m.type==='generate-job'&&!cmsConfig.industryEnabled)return;const target=projects.find(p=>p.id===m.projectId)||project;if(m.type==='preview'){setModal(null);setPreviewId(project.id);return;}setPreviewId(null);if(m.type==='content'&&!m.content&&['knowledge','unit'].includes(m.source)){setModal({...m,type:'associate'});return;}setError('');setModal(['generate','generate-job'].includes(m.type)?{...m,projectId:target.id}:m);setForm(m.type==='stage-edit'?{title:m.title||''}:m.type==='task-edit'?{title:m.title||''}:m.type==='project-edit'?{title:target.title,description:target.description||'',icon:target.icon||'project-stack',titleEn:target.titleEn||'',descriptionEn:target.descriptionEn||''}:m.type==='content'?{title:m.content?.title||'',kind:m.content?.type||contentSources[m.source]?.type||'学习单元',scored:m.content?.scored??contentSources[m.source]?.scored??false,source:m.content?.source||m.source||'',file:m.content?.file||null}:{title:m.title||'',description:'',icon:'project-stack',titleEn:'',descriptionEn:''});};
 const close=()=>setModal(null);
 const save=()=>{if(modal.type==='content'&&form.source==='file'&&!form.file){setError('请先选择本地文件');return;}if(!form.title?.trim()){setError('请输入名称');return;}if(modal.type.startsWith('project')&&!form.description?.trim()){setError('请输入项目描述');return;}if(modal.type==='project-create'){const p=createProject(form.title.trim(),form.description.trim());Object.assign(p,{icon:form.icon,titleEn:form.titleEn.trim(),descriptionEn:form.descriptionEn.trim()});setProjects(ps=>[...ps,p]);setActiveId(p.id);setSection('project');setTab('课程模型');}else mutate(p=>{if(modal.type==='project-edit'){p.title=form.title.trim();p.description=form.description.trim();Object.assign(p,{icon:form.icon,titleEn:form.titleEn.trim(),descriptionEn:form.descriptionEn.trim()});if(p.learningDesign){p.learningDesign.title=p.title;p.learningDesign.problem=p.description;}}else{const s=p.stages.find(s=>s.id===modal.stageId);if(modal.type==='stage-edit'){s.title=form.title.trim();}else{const t=s.tasks.find(t=>t.id===modal.taskId);if(modal.type==='task-edit'){t.title=form.title.trim();}else{const content={...modal.content,id:modal.content?.id||id(),title:form.title.trim(),type:form.kind,scored:form.scored,...(form.source?{source:form.source}:{}),...(form.file?{file:form.file}:{})};if(modal.content)t.contents=t.contents.map(c=>c.id===content.id?content:c);else t.contents.push(content);}}}},modal.projectId||project?.id);setModal(null);setToast('已保存');};
 const remove=()=>{if(modal.type==='delete-project'){const remaining=projects.filter(p=>p.id!==modal.projectId);setProjects(remaining);if(project?.id===modal.projectId)setActiveId(remaining[0]?.id||null);}else mutate(p=>{if(modal.type==='delete-stage')p.stages=p.stages.filter(s=>s.id!==modal.stageId);else{const s=p.stages.find(s=>s.id===modal.stageId);s.tasks=s.tasks.filter(t=>t.id!==modal.taskId);}});setModal(null);setToast('已删除');};
 const currentTitle=tab==='课程模型'?section:tab;
 const isForm=modal&&['project-create','project-edit','stage-edit','task-edit','content'].includes(modal.type);
 const isProjectForm=modal?.type==='project-create'||modal?.type==='project-edit';
 const modalTitle=isForm?({'project-create':'新增','project-edit':'修改','stage-edit':'编辑阶段','task-edit':'编辑任务','content':modal.content?'编辑任务内容':`添加${contentSources[modal.source]?.label||'任务内容'}`}[modal.type]):modal?.type==='publish'?'发布项目':'删除确认';
 return <div className={`app ${collapsed?'sidebar-collapsed':''}`}>
 <aside className="global-rail"><div className="brand"><Icon name="school" size={24}/></div><div className="rail-bottom"><button title="教学助手" aria-label="教学助手" onClick={()=>setTab('AI应用')}><Icon name="robot" size={26}/></button><button title="课程知识库" aria-label="课程知识库" onClick={()=>setTab('知识库')}><Icon name="books" size={25}/></button><button title="导出项目草稿" aria-label="导出项目草稿" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(projects,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='AI课程项目草稿.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setToast('已导出项目草稿');}}><Icon name="download" size={25}/></button><div className="rail-line"/><span>AI 课程</span></div></aside>
 <header className="topbar"><div className="course-name"><span className="ai-mark">AI</span>{courseName}</div><a className="course-cms-entry" href={cmsHref(cmsConfig)}>课程 CMS</a><nav aria-label="顶部菜单">{tabs.map(([name,icon])=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}><Icon name={icon}/>{name}</button>)}</nav><button className={`members ${tab==='成员'?'selected':''}`} onClick={()=>setTab('成员')}><Icon name="users" size={16}/>成员</button></header>
 <aside className="course-sidebar"><button className="collapse-sidebar icon-button" aria-label={collapsed?'展开侧栏':'收起侧栏'} onClick={()=>setCollapsed(!collapsed)}><Icon name="collapse" size={16}/></button>{!collapsed&&<>
 {groups.map(g=><section className="nav-group" key={g.label}><h2>{g.label}</h2>{g.items.map(([name,desc,icon,color])=><button key={name} className={`nav-item ${tab==='课程模型'&&section===name?'selected':''}`} onClick={()=>{setTab('课程模型');setSection(name);}}><span className={`nav-icon ${color}`}><Icon name={icon} size={23}/></span><span><strong>{name}</strong><small>{desc}</small></span></button>)}</section>)}
 <section className="nav-group projects-nav"><h2>项目式学习</h2>{projects.map(p=><div className="project-nav-row" key={p.id}><button className={`nav-item ${tab==='课程模型'&&section==='project'&&p.id===project?.id?'selected':''}`} onClick={()=>{setTab('课程模型');setSection('project');setActiveId(p.id);}}><span className="nav-icon blue"><Icon name={p.icon||'project-stack'} size={24}/></span><span><strong>{p.title}</strong><small>{p.description||'项目式学习'}</small></span></button><ProjectActions project={p} onEdit={target=>open({type:'project-edit',projectId:target.id})} onDelete={target=>open({type:'delete-project',projectId:target.id,title:target.title})}/></div>)}<button className="outlined add-project" onClick={()=>open({type:'project-create'})}><Icon name="plus"/>项目式学习</button></section>
 <section className="nav-group last"><h2>增强知识库</h2><button className={`nav-item ${section==='增强知识库'&&tab==='课程模型'?'selected':''}`} onClick={()=>{setTab('课程模型');setSection('增强知识库');}}><span className="nav-icon violet"><Icon name="chart" size={23}/></span><span><strong>增强知识库</strong><small>增强知识库</small></span></button></section>
 </>}</aside>
 <main>{tab==='课程模型'&&section==='知识图谱'?<KnowledgeGraph graph={graph} setGraph={setGraph} projects={projects} onResources={()=>setTab('知识库')} onProject={()=>setSection('project')}/>:tab==='课程模型'&&section==='project'?(!project?<section className="module-page empty-projects"><div className="module-empty"><span className="empty-icon"><Icon name="project-stack" size={44}/></span><h2>暂无项目</h2><p>创建项目，开始设计项目式学习内容。</p><button className="primary" onClick={()=>open({type:'project-create'})}><Icon name="plus"/>新增项目式学习</button></div></section>:previewId===project.id?<ProjectPreview cmsConfig={cmsConfig} project={project} projects={projects} knowledge={graph} onExit={()=>setPreviewId(null)}/>:<ProjectEditor cmsConfig={cmsConfig} industryEnabled={cmsConfig.industryEnabled} project={project} mutate={mutate} open={open}/>):<section className="module-page"><div className="module-heading"><div><p>智能制造岗位项目课程</p><h1>{currentTitle}</h1><span>{descriptions[currentTitle]}</span></div><span className="framework-tag">课程框架</span></div><div className="module-empty"><span className="empty-icon"><Icon name={tabs.find(t=>t[0]===tab)?.[1]||'graph'} size={44}/></span><h2>{currentTitle==='成员'?'课程成员工作区':`${currentTitle}工作区`}</h2><p>课程入口已就绪，内容将在后续课程建设中配置。</p><button className="primary" onClick={()=>{setTab('课程模型');setSection('project');}}><Icon name="stack"/>进入项目式学习</button></div>{['知识图谱','能力图谱','问题图谱','素质图谱'].includes(currentTitle)&&<div className="relationship-note"><Icon name="info"/>后续可将{currentTitle.replace('图谱','')}关联到项目任务，形成课程与实践的联系。</div>}</section>}</main>
 {toast&&<div className="toast" role="status"><Icon name="check"/>{toast}</div>}
 {modal?.type==='generate-job'&&<GenerationWizard graph={graph} resources={courseResources} courseId="local-smart-manufacturing" courseMajor={cmsConfig.major} cmsConfig={cmsConfig} courseName={courseName} onClose={close} onCreate={generated=>{setProjects(ps=>ps.map(p=>p.id===modal.projectId?{...p,...generated,id:p.id}:p));setActiveId(modal.projectId);setModal(null);setToast('已覆盖当前项目数据，可继续编辑调整');}}/>}
 {modal?.type==='generate'&&<FrameworkDialog project={projects.find(p=>p.id===modal.projectId)||project} onClose={close} onGenerate={()=>{mutate(p=>{p.stages=[];delete p.learningDesign;appendTemplate(p);},modal.projectId);close();setToast('已覆盖当前项目框架，可继续编辑调整');}}/>}
 {modal?.type==='associate'&&<ContentAssociation source={modal.source} graph={graph} resources={courseResources} task={project.stages.find(stage=>stage.id===modal.stageId).tasks.find(task=>task.id===modal.taskId)} onClose={close} onConfirm={selectedIds=>{mutate(p=>{const stage=p.stages.find(stage=>stage.id===modal.stageId);stage.tasks=stage.tasks.map(task=>task.id===modal.taskId?associateContents(task,modal.source,selectedIds,graph,courseResources):task);});setModal(null);setToast('已关联到任务');}}/>}
 {modal&&!['generate','generate-job','associate'].includes(modal.type)&&<Modal title={modalTitle} hideHeader={modal.type==='delete-project'} className={isProjectForm?'project-metadata-modal':modal.type==='delete-project'?'project-delete-modal':''} onClose={close} footer={<>{isForm?<><button className="outlined" onClick={close}>取消</button><button className="primary" disabled={isProjectForm&&(!form.title?.trim()||!form.description?.trim())} onClick={save}>{isProjectForm?'确定':'保存'}</button></>:modal.type?.startsWith('delete')?<><button className="outlined" onClick={close}>取消</button><button className="danger" onClick={remove}>{modal.type==='delete-project'?'确定':'确认删除'}</button></>:modal.type==='publish'?<><button className="outlined" onClick={close}>取消</button><button className="primary" onClick={()=>{const message=validateProject(project);if(message)setError(message);else{open({type:'preview'});setToast('已打开发布预览，尚未向班级发布');}}}>查看发布预览</button></>:<button className="primary" onClick={close}>返回编辑</button>}</>}>
 {isProjectForm?<ProjectForm form={form} setForm={setForm} onSave={save}/>:isForm?<form onSubmit={e=>{e.preventDefault();save();}}><label>{modal.type==='content'?'内容名称':'名称'}<input readOnly={!!(modal.content?.knowledgeNodeId||modal.content?.resourceId)} autoFocus placeholder="请输入名称" value={form.title} maxLength={80} onChange={e=>setForm({...form,title:e.target.value})}/></label>{modal.type.startsWith('project')&&<label>项目简介<textarea rows={3} placeholder="简要描述项目内容与学习目标" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>}{modal.type==='content'&&<>{form.source?<div className="content-source-summary"><Icon name={contentSources[form.source].icon}/><strong>{contentSources[form.source].label}</strong><span>{form.scored?'计分':'不计分'}</span></div>:<><label>内容类型<select value={form.kind} onChange={e=>setForm({...form,kind:e.target.value})}>{['目标','学习单元','拓展学习'].map(t=><option key={t}>{t}</option>)}</select></label><label className="checkbox"><input type="checkbox" checked={form.scored} onChange={e=>setForm({...form,scored:e.target.checked})}/>纳入计分</label></>}{form.source==='file'?<><label>选择本地文件<input type="file" onChange={e=>{const file=e.target.files?.[0];if(file)setForm({...form,title:file.name,file:{name:file.name,size:file.size,mimeType:file.type}});}}/></label>{form.file&&<p className="form-hint">已选择：{form.file.name}</p>}<p className="form-hint">草稿仅保存文件名称与信息，文件尚未上传。</p></>:<p className="form-hint">{modal.content?.knowledgeNodeId||modal.content?.resourceId?'内容名称与所关联的知识点或学习单元保持一致。':'先保存内容名称，具体资源选择与关联将在接入课程资源后提供。'}</p>}{modal.content&&<button type="button" className="delete-content" onClick={()=>{mutate(p=>{const t=p.stages.find(s=>s.id===modal.stageId).tasks.find(t=>t.id===modal.taskId);t.contents=t.contents.filter(c=>c.id!==modal.content.id);});setModal(null);setToast('已删除任务内容');}}>删除这条内容</button>}</>}</form>:modal.type==='publish'?<><p>发布前请检查项目阶段、任务与学习内容。</p><div className="publish-info"><Icon name="info"/><span>当前是课程框架演示，尚未连接教学班级。可查看发布预览，不会向学生发布。</span></div></>:modal.type==='delete-project'?<p>项目（{modal.title}）删除后不可恢复，是否删除？</p>:<p>确定删除「{modal.title}」？该{modal.type==='delete-stage'?'阶段及其全部任务、学习内容':'任务及其学习内容'}会一并删除。</p>}
 {error&&<p className="form-error" role="alert">{error}</p>}
 </Modal>}
 </div>;
}
