import { useEffect, useMemo, useState } from 'react';
import { createPortal } from 'react-dom';
import { Icon } from '../components/Icon';
import { Modal } from '../components/Modal';
import { GraphCanvas } from './GraphCanvas';
import { KNOWLEDGE_STORAGE, descendants, graphStats, updateKnowledgeNode } from './model.mjs';
import './knowledge.css';
import { KnowledgeJobRelations } from './KnowledgeJobRelations';
import { knowledgeJobRelations, removeKnowledgeJobRelation } from './job-relations.mjs';
import { useKnowledgeEnabled } from './availability.mjs';
import { EmptyKnowledgeGraph, KnowledgeDemoSwitch } from './KnowledgeDemoSwitch';
const levelNames=['一级','二级','三级','四级'];
export function KnowledgeGraph(props){
 const enabled=useKnowledgeEnabled();
 return <>{enabled?<PopulatedKnowledgeGraph {...props}/>:<EmptyKnowledgeGraph {...props}/>}<KnowledgeDemoSwitch/></>;
}
function PopulatedKnowledgeGraph({graph,setGraph,projects=[],onResources,onProject}){
 const [query,setQuery]=useState(''),[ideologyOnly,setIdeologyOnly]=useState(false),[catalog,setCatalog]=useState(false),[editing,setEditing]=useState(false),[selected,setSelected]=useState(null),[detailTab,setDetailTab]=useState('知识点详情'),[expanded,setExpanded]=useState([]),[level,setLevel]=useState(3),[relation,setRelation]=useState('层级'),[zoom,setZoom]=useState(100),[pan,setPan]=useState({x:0,y:0}),[draft,setDraft]=useState({}),[error,setError]=useState(''),[message,setMessage]=useState(''),[share,setShare]=useState(false),[sidebar,setSidebar]=useState(null);
 const stats=useMemo(()=>graphStats(graph),[graph]);const node=graph.nodes.find(n=>n.id===selected);const children=node?graph.nodes.filter(n=>n.parentId===node.id):[];
 const demoPoint=graph.nodes.find(n=>(graph.demoJobProjects||[]).some(p=>p.stages.some(s=>s.tasks.some(t=>t.contents.some(c=>c.knowledgeNodeId===n.id))))&&knowledgeJobRelations(graph,[],n.id).length);
 const results=ideologyOnly?graph.nodes.filter(n=>n.ideology):query.trim()?graph.nodes.filter(n=>n.name.toLowerCase().includes(query.trim().toLowerCase())):[];
 useEffect(()=>{setSidebar(document.querySelector('.course-sidebar'));},[]);
 useEffect(()=>{if(message){const t=setTimeout(()=>setMessage(''),3000);return()=>clearTimeout(t);}},[message]);
 const choose=id=>{const n=graph.nodes.find(n=>n.id===id);if(n.level===4)setExpanded(prev=>[...new Set([...prev,n.parentId])]);setSelected(id);setDraft({name:n.name,desc:n.desc||'',ideology:n.ideology||'',design:n.design||''});setDetailTab('知识点详情');setError('');};
 const save=()=>{try{const next=updateKnowledgeNode(graph,node.id,draft);setGraph(next);try{localStorage.setItem(KNOWLEDGE_STORAGE,JSON.stringify(next));setMessage('知识点已保存');}catch{setMessage('已更新，浏览器未允许保存草稿');}setSelected(null);}catch(e){setError(e.message);}};
 const removeJobRelation=relationId=>{const next=removeKnowledgeJobRelation(graph,relationId);setGraph(next);try{localStorage.setItem(KNOWLEDGE_STORAGE,JSON.stringify(next));setMessage('已删除岗位关系');}catch{setMessage('已删除，浏览器未允许保存，请保持页面打开');}};
 const download=()=>{const blob=new Blob([JSON.stringify(graph,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='智能制造知识图谱.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setMessage('已导出完整图谱数据');};
 const tree=(parentId,depth=0)=>graph.nodes.filter(n=>n.parentId===parentId).map(n=><div key={n.id} className="kg-tree-node">{n.level<4?<details open={depth<1}><summary><button onClick={()=>choose(n.id)} title={n.name}><i className={`kg-dot l${n.level}`}/>{n.name}</button><small>{descendants(graph,n.id).length}</small></summary>{tree(n.id,depth+1)}</details>:<button className="kg-tree-leaf" onClick={()=>choose(n.id)}><i className="kg-dot l4"/>{n.name}</button>}</div>);
 return <section className={`knowledge-board ${editing?'is-editing':''}`} aria-label="课程知识图谱">
  <GraphCanvas graph={graph} selected={selected} onSelect={choose} expanded={expanded} level={level} relation={relation} zoom={zoom} pan={pan} setPan={setPan}/>
  <aside className={`kg-stat-card ${catalog?'catalog-open':''}`}>
   <h2>知识点总量（条）</h2><strong className="kg-total">{stats.total}</strong><label className="kg-search"><Icon name="search" size={17}/><input placeholder="搜索" aria-label="搜索知识点" value={query} onChange={e=>{setQuery(e.target.value);setIdeologyOnly(false);}}/>{(query||ideologyOnly)&&<button aria-label="清空搜索" onClick={()=>{setQuery('');setIdeologyOnly(false);}}><Icon name="close" size={13}/></button>}</label>
   {(query.trim()||ideologyOnly)?<div className="kg-results"><div className="kg-result-count">找到 {results.length} 个知识点</div>{results.length?results.map(n=><button key={n.id} onClick={()=>choose(n.id)}><i className={`kg-dot l${n.level}`}/><span>{n.name}<small>{levelNames[n.level-1]}知识点</small></span><Icon name="arrow" size={13}/></button>):<p>未找到相关知识点</p>}</div>:catalog?<div className="kg-catalog"><button className="kg-tree-root" onClick={()=>choose('root')}><i className="kg-dot l1"/>智能制造</button>{tree('root')}</div>:<><div className="kg-levels">{stats.levels.map((n,i)=><button key={i} onClick={()=>{setLevel(i+1);setZoom(i===3?80:100);setPan({x:0,y:0});}}><i className={`kg-dot l${i+1}`}/><span>{levelNames[i]}<em>({n})</em></span></button>)}<button onClick={()=>{setIdeologyOnly(true);setQuery('');}}><Icon name="star" size={13} weight="fill" color="#ff81aa"/><span>思政点<em>({stats.ideology})</em></span></button></div><div className="kg-relations"><button onClick={()=>{setRelation('先后修');setLevel(4);setZoom(80);}}><span className="kg-line-legend"><Icon name="arrow" size={27}/></span>先后修</button><button onClick={()=>{setRelation('相关');setLevel(4);setZoom(80);}}><span className="kg-dashed-legend"/>相关</button><p><i className="kg-dot resource"/>关联学习内容(0个)</p><p><i className="kg-dot exercise"/>关联习题(0个)</p></div></>}
   <footer><button onClick={()=>{setCatalog(!catalog);setQuery('');setIdeologyOnly(false);}}><Icon name={catalog?'graph':'list'} size={16}/>{catalog?'图例':'目录'}</button><button onClick={download}><Icon name="download" size={16}/>下载</button></footer>
  </aside>
  <div className="kg-toolbar">{demoPoint&&<button className="kg-edit-button kg-job-demo-entry" onClick={()=>{choose(demoPoint.id);setDetailTab('岗位关系');}}><Icon name="users" size={17}/>岗位关系示例</button>}<div className="kg-view-tools"><label title="显示层级"><Icon name="tree"/><select aria-label="显示层级" value={level} onChange={e=>{const value=+e.target.value;setLevel(value);setZoom(value===4?80:100);}}><option value={1}>一级节点</option><option value={2}>二级节点</option><option value={3}>三级节点</option><option value={4}>全部节点</option></select><Icon name="down" size={12}/></label><label title="节点关系"><Icon name="graph"/><select aria-label="节点关系" value={relation} onChange={e=>{setRelation(e.target.value);if(e.target.value!=='层级'){setLevel(4);setZoom(80);}}}><option value="层级">层级关系</option><option value="先后修">先后修</option><option value="相关">相关</option></select><Icon name="down" size={12}/></label></div><button className={`kg-edit-button ${editing?'active':''}`} onClick={()=>{setEditing(!editing);setSelected(null);}}><Icon name={editing?'close':'edit'} size={18}/>{editing?'退出编辑':'编辑'}</button></div>
  {editing&&<div className="kg-edit-hint"><Icon name="info" size={15}/>点击知识点，可编辑名称、说明与思政设计</div>}
  <div className="kg-zoom"><button aria-label="重置图谱视图" title="重置视图" onClick={()=>{setZoom(100);setPan({x:0,y:0});setExpanded([]);setLevel(3);setRelation('层级');}}><Icon name="crosshair" size={21}/></button><span/><button aria-label="缩小图谱" onClick={()=>setZoom(z=>Math.max(50,z-10))}><Icon name="minus-circle" size={20}/></button><input aria-label="图谱缩放" type="range" min="50" max="150" step="10" value={zoom} onChange={e=>setZoom(+e.target.value)}/><button aria-label="放大图谱" onClick={()=>setZoom(z=>Math.min(150,z+10))}><Icon name="plus-circle" size={20}/></button><strong>{zoom}%</strong></div>
  {node&&<><div className="kg-drawer-shade" onClick={()=>setSelected(null)}/><aside className="kg-detail" aria-label="知识点详情面板"><header><nav>{['知识点详情','节点关系','学习内容','思政设计','岗位关系'].map(t=><button key={t} className={detailTab===t?'active':''} onClick={()=>setDetailTab(t)}>{t}</button>)}</nav><button className="icon-button" aria-label="关闭知识点详情" onClick={()=>setSelected(null)}><Icon name="close"/></button></header><div className="kg-detail-body"><div className="kg-breadcrumb">智能制造{node.parentId&&node.parentId!=='root'?` / ${graph.nodes.find(n=>n.id===node.parentId)?.name}`:''}</div><h2>{node.name}</h2><div className="kg-node-tags"><span>{levelNames[node.level-1]}知识点</span>{node.type&&<span>{node.type}</span>}{node.priority&&<span>{node.priority}</span>}{node.cognition&&<span>{node.cognition}</span>}</div>
  {detailTab==='岗位关系'?<KnowledgeJobRelations graph={graph} projects={projects} nodeId={node.id} onRemove={removeJobRelation} onProject={onProject}/>:detailTab==='知识点详情'?<>{editing?<><label>知识点名称<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label><label>知识说明<textarea rows={5} value={draft.desc} onChange={e=>setDraft({...draft,desc:e.target.value})}/></label></>:<div className="kg-description"><h3>知识说明</h3><p>{node.desc||'暂无知识说明'}</p></div>}{children.length>0&&<section className="kg-children"><h3>下级知识点 <small>{children.length}</small></h3>{children.map(n=><button key={n.id} onClick={()=>choose(n.id)}><i className={`kg-dot l${n.level}`}/>{n.name}<Icon name="arrow" size={15}/></button>)}{node.level===3&&<button className="outlined" onClick={()=>{setExpanded(prev=>[...new Set([...prev,node.id])]);setSelected(null);}}>在图谱中展开节点</button>}</section>}<p className="kg-source">数据来源：既有《智能制造》课程图谱示例</p></>:detailTab==='节点关系'?<section className="kg-link-list">{graph.links.filter(l=>l.source===node.id||l.target===node.id).map((l,i)=>{const other=graph.nodes.find(n=>n.id===(l.source===node.id?l.target:l.source));return <button key={i} onClick={()=>choose(other.id)}><span>{l.type==='层级'?(l.source===node.id?'下级':'上级'):l.type==='先后修'?(l.source===node.id?'后修':'先修'):'相关'}</span>{other.name}<Icon name="arrow" size={14}/></button>;})}</section>:detailTab==='学习内容'?<div className="kg-detail-empty"><Icon name="book" size={36}/><h3>尚未关联学习内容</h3><p>可先在项目式学习中建设任务内容。</p><button className="outlined" onClick={onProject}>进入项目式学习</button></div>:<section className="kg-civic">{editing?<><label>思政元素<input placeholder="填写思政元素" value={draft.ideology} onChange={e=>setDraft({...draft,ideology:e.target.value})}/></label><label>设计方式<textarea rows={6} placeholder="描述思政元素如何融入教学" value={draft.design} onChange={e=>setDraft({...draft,design:e.target.value})}/></label></>:<><h3>{node.ideology||'尚未设置思政元素'}</h3><p>{node.design||'进入编辑模式后，可补充思政元素与设计方式。'}</p></>}</section>}{error&&<p className="form-error" role="alert">{error}</p>}</div><footer>{editing?<><button className="outlined" onClick={()=>setSelected(null)}>取消</button><button className="primary" onClick={save}>保存修改</button></>:<button className="outlined" onClick={()=>setSelected(null)}>关闭</button>}</footer></aside></>}
  {message&&<div className="toast" role="status"><Icon name="check"/>{message}</div>}
  {share&&<Modal title="开放图谱到班级" onClose={()=>setShare(false)} footer={<button className="primary" onClick={()=>setShare(false)}>知道了</button>}><p>图谱已可预览，共 {stats.total} 个知识点。</p><div className="publish-info"><Icon name="info"/><span>当前尚未连接教学班级，开放与班级选择将在教学空间接入后启用。</span></div></Modal>}
  {sidebar&&createPortal(<div className="kg-sidebar-footer"><button className="primary" onClick={()=>setShare(true)}><Icon name="graph" size={17}/>开放图谱到班级</button><button onClick={onResources}>管理资源</button></div>,sidebar)}
 </section>;
}
