import { Icon } from './Icon';
import { createStage, createTask, projectStats } from '../project.mjs';
const ord=['一','二','三','四','五','六','七','八','九','十'];
export function ProjectEditor({project,mutate,open}){
 const stats=projectStats(project);
 return <div className="project-page">
  <section className="project-hero"><div className="hero-info"><button className="project-title" onClick={()=>open({type:'project-edit'})}>{project.title}<Icon name="edit" size={16}/></button><p>{project.description||'添加项目简介，明确项目学习方向'}</p><div className="stats">{[['阶段',stats.stages],['任务',stats.tasks],['学习单元',stats.units],['拓展学习',stats.extensions]].map(([label,n])=><div className="stat" key={label}><span>{label}{['学习单元','拓展学习'].includes(label)&&<Icon name="info" size={12}/>}</span><strong>{n}</strong></div>)}</div></div><div className="hero-actions"><div><button onClick={()=>open({type:'generate'})}><Icon name="sparkle"/>AI 生成框架</button><button onClick={()=>open({type:'preview'})}><Icon name="eye"/>预览</button></div><button className="publish" onClick={()=>open({type:'publish'})}><Icon name="send"/>发布项目</button></div></section>
  <div className="unlock"><span>顺序解锁 <span title="开启后，学习者需按阶段顺序完成学习"><Icon name="info" size={14}/></span></span><button className={`switch ${project.sequential?'on':''}`} role="switch" aria-label="顺序解锁" aria-checked={project.sequential} onClick={()=>mutate(p=>{p.sequential=!p.sequential;})}><span/></button></div>
  <div className="stage-list">{project.stages.map((stage,i)=><section key={stage.id} className={`stage stage-${i%3}`}><header className="stage-header"><Icon name="drag" size={17}/><span className="stage-number">{String(i+1).padStart(2,'0')}</span><button className="stage-title" onClick={()=>open({type:'stage-edit',stageId:stage.id,title:stage.title})}>阶段{ord[i]||i+1}：{stage.title}</button><div className="stage-controls"><button className="icon-button" aria-label={`删除阶段${i+1}`} onClick={()=>open({type:'delete-stage',stageId:stage.id,title:stage.title})}><Icon name="trash"/></button><button className="icon-button" aria-label={`${stage.collapsed?'展开':'收起'}阶段${i+1}`} onClick={()=>mutate(p=>{p.stages[i].collapsed=!stage.collapsed;})}><Icon name={stage.collapsed?'down':'up'}/></button></div></header>
  {!stage.collapsed&&<div className="stage-body"><div className="tasks-card">{stage.tasks.map((task,j)=><article className="task" key={task.id}><header><Icon name="drag" size={16}/><button className="task-title" onClick={()=>open({type:'task-edit',stageId:stage.id,taskId:task.id,title:task.title})}>任务{j+1} {task.title}</button><button className="icon-button" aria-label={`删除任务${i+1}-${j+1}`} onClick={()=>open({type:'delete-task',stageId:stage.id,taskId:task.id,title:task.title})}><Icon name="trash" size={17}/></button><button className="icon-button" aria-label={`${task.collapsed?'展开':'收起'}任务${i+1}-${j+1}`} onClick={()=>mutate(p=>{p.stages[i].tasks[j].collapsed=!task.collapsed;})}><Icon name={task.collapsed?'down':'up'} size={17}/></button></header>{!task.collapsed&&<div className="task-body">{task.contents.map(c=><button key={c.id} className="content-row" onClick={()=>open({type:'content',stageId:stage.id,taskId:task.id,content:c})}><Icon name={c.type==='目标'?'target':'book'} size={18}/><span>{c.title}</span><em className={c.scored?'scored':''}>{c.scored?'计分':c.type}</em></button>)}<button className="add-content" onClick={()=>open({type:'content',stageId:stage.id,taskId:task.id})}>添加任务内容</button></div>}</article>)}<button className="new-task" onClick={()=>mutate(p=>{p.stages[i].tasks.push(createTask());})}><Icon name="plus"/>创建新任务</button></div></div>}</section>)}<button className="add-stage" onClick={()=>mutate(p=>{const s=createStage();s.tasks=[createTask()];p.stages.push(s);})}><Icon name="plus" size={17}/>添加阶段</button></div>
 </div>;
}
