import {useState} from 'react';
import {COURSE_TIERS} from './config.mjs';
const empty={name:'',school:'',platform:'',delivery:'',open:'',source:'',type:'',tier:'',contractTier:'',contract:'',online:'',tag:''};
const fields=[['platform','所属平台',['教学平台']],['delivery','交付状态',['待交付','已交付']],['open','是否开放',['是','否']],['source','来源',['学堂自研 - 智谱GLM-4-Plus']],['type','类型',['共建课程-项目式教学']],['tier','AI课档位',COURSE_TIERS],['contractTier','合同档位',COURSE_TIERS],['contract','合同状态',['未签订','已签订']],['online','是否上架 xuetang.ai',['是','否']],['tag','标签筛选',['项目式教学']]];
export function CourseList({saved,onManage}){
 const [filters,setFilters]=useState(empty),[query,setQuery]=useState(empty),[more,setMore]=useState(true),[tab,setTab]=useState('AI课管理'),[notice,setNotice]=useState('');
 const row={name:'智能制造岗位项目课程',id:'local-smart-manufacturing',school:'',platform:'教学平台',delivery:'',open:'是',source:'学堂自研 - 智谱GLM-4-Plus',type:'共建课程-项目式教学',tier:saved.tier,contractTier:'',contract:'',online:'否',tag:'项目式教学'};
 const visible=Object.entries(query).every(([key,value])=>!value||(key==='name'?`${row.name} ${row.id}`.includes(value):key==='school'?row.school.includes(value):row[key]===value));
 const select=([key,label,options])=><label key={key}>{label}<select aria-label={`筛选${label}`} value={filters[key]} onChange={e=>setFilters({...filters,[key]:e.target.value})}><option value="">请选择</option>{options.map(option=><option key={option}>{option}</option>)}</select></label>;
 return <section className="cms-panel cms-course-list"><div className="cms-tabs">{['AI课管理','AI课使用','AI课运营管理'].map(name=><button key={name} className={tab===name?'active':''} onClick={()=>setTab(name)}>{name}</button>)}</div>{tab==='AI课管理'?<><form className="cms-filters" onSubmit={e=>{e.preventDefault();setQuery({...filters});}}><label>课程名称或课程id<input aria-label="课程名称或课程id" placeholder="课程名称或课程id" value={filters.name} onChange={e=>setFilters({...filters,name:e.target.value})}/></label><label>所属学校<input aria-label="所属学校" placeholder="输入所属学校名" value={filters.school} onChange={e=>setFilters({...filters,school:e.target.value})}/></label>{fields.slice(0,2).map(select)}<button type="button" className="cms-link" onClick={()=>setMore(!more)}>{more?'收起更多筛选项':'展开更多筛选项'}</button>{more&&<div className="cms-extra-filters">{fields.slice(2).map(select)}</div>}<div className="cms-query-actions"><button className="primary" type="submit">查询</button><button type="button" className="cms-link" onClick={()=>{setFilters({...empty});setQuery({...empty});}}>清空</button></div></form><div className="cms-list-toolbar"><span>共查询到 {visible?1:0} 条结果</span><button className="primary" onClick={()=>setNotice('当前演示仅配置已有课程，尚未接入创建 AI 课服务。')}>创建AI课</button></div>{notice&&<p role="status" className="cms-list-notice">{notice}</p>}<div className="cms-table-scroll"><table><thead><tr>{['AI课程ID','名称','是否开放','来源','类型','所属学校','所属平台','操作'].map(name=><th key={name}>{name}</th>)}</tr></thead><tbody>{visible?<tr><td>{row.id}</td><td>{row.name}</td><td>{row.open}</td><td>{row.source}</td><td>{row.type}</td><td>未配置</td><td>{row.platform}</td><td><button className="cms-link" aria-label="配置课程" onClick={onManage}>管理</button></td></tr>:<tr><td colSpan="8" className="cms-no-results">暂无符合筛选条件的课程</td></tr>}</tbody></table></div><nav className="cms-pagination" aria-label="课程列表分页"><span>共 {visible?1:0} 条</span><button disabled aria-label="上一页">‹</button><button className="active" aria-current="page">1</button><button disabled aria-label="下一页">›</button></nav></>:<div className="cms-empty">暂无{tab==='AI课使用'?'课程使用':'课程运营'}数据</div>}</section>;
}
