import {JobMatching} from './JobMatching';
import {useState,useEffect} from 'react';
import {CourseList} from './CourseList';
import {CourseMajorDialog} from './CourseMajorDialog';
import {COURSE_TIERS,chains,initialConfig,saveConfig,changeMajor,matchChains,courseHref,normalizeConfig} from './config.mjs';
import '../generation/generation.css';
import './cms.css';
export function CourseCMS(){
 useEffect(()=>{document.title='课程 CMS · AI 课程管理';},[]);
 const [saved,setSaved]=useState(initialConfig),[draft,setDraft]=useState(saved),[page,setPage]=useState('list'),[all,setAll]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('');
 const [activeTab,setActiveTab]=useState('基础信息');
 const [majorDialog,setMajorDialog]=useState(false);
 const matches=matchChains(draft.major?.code),shown=all?chains:matches;
 const persist=()=>{try{const next=saveConfig(draft);setSaved(next);setDraft(next);setError('');setNotice('课程配置已保存');return next;}catch{setError('浏览器未能保存配置，请使用“保存并返回课程”将配置带回课程页面。');return null;}};
 const toggleChain=id=>{setNotice('');setDraft(value=>normalizeConfig({...value,chainIds:value.chainIds.includes(id)?value.chainIds.filter(item=>item!==id):[...value.chainIds,id]}));};
 return <div className="course-cms"><aside className="cms-nav"><nav aria-label="CMS 管理菜单">{['cms管理','资源管理','课程管理','商品管理','服务等级'].map(name=><div className="cms-menu-section" key={name}><span>▦</span>{name}<em>⌄</em></div>)}<div className="cms-menu-section expanded"><span>▦</span>平台管理<em>⌃</em></div><div className="cms-sub-menu">{['平台列表','班级管理','平台通知','直播分发','操作日志','直播管理','新版克隆班'].map(name=><div key={name}><span>▦</span>{name}</div>)}<button className="active" onClick={()=>{setPage('list');setDraft(saved);setNotice('');setError('');}}><span>▦</span>AI 课程</button>{['平台AI','AI课门户','数字人管理','批量删除用户权限'].map(name=><div key={name}><span>▦</span>{name}</div>)}</div></nav></aside><div className="cms-content"><header><div className="cms-breadcrumb"><span className="cms-hamburger">☰</span><span>平台管理 / AI 课程管理</span></div><div className="cms-user-tools"><span>⌄ 工单</span><span className="cms-avatar">Tre</span></div></header><main><article className="cms-management-card">
 <div className="cms-page-heading" hidden={page==='list'}><div className="cms-heading-title">{page==='edit'&&<><button aria-label="返回课程列表" onClick={()=>{setPage('list');setDraft(saved);}}>‹</button><i/></>}<div><h1>{page==='list'?'AI 课程管理':'课程建设'}</h1>{page==='edit'&&<p>课程名称：智能制造岗位项目课程</p>}</div></div><a className="outlined" href={courseHref(saved)}>进入课程 ↗</a></div>
 {page==='edit'&&<nav className="cms-management-tabs" role="tablist" aria-label="课程管理页签">{[['基础信息','cms-basic'],...(draft.tier!=='培育课'?[['产教模型','cms-industry']]:[])].map(([name,panel],index)=><button key={panel} type="button" role="tab" id={`${panel}-tab`} aria-controls={panel} aria-selected={activeTab===name} tabIndex={activeTab===name?0:-1} className={activeTab===name?'active':''} onClick={()=>setActiveTab(name)} onKeyDown={event=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const target=draft.tier==='培育课'?0:event.key==='Home'?0:event.key==='End'?1:1-index;setActiveTab(target===0?'基础信息':'产教模型');event.currentTarget.parentElement.querySelectorAll('[role="tab"]')[target].focus();}}}>{name}</button>)}</nav>}

 {page==='list'?<CourseList saved={saved} onManage={()=>{setDraft(saved);setActiveTab('基础信息');setPage('edit');}}/>:<>
 <section id="cms-basic" role="tabpanel" aria-labelledby="cms-basic-tab" hidden={activeTab!=='基础信息'} className="cms-panel"><div className="cms-section-heading"><div><h2>课程基础信息</h2><p>设置课程关联专业，项目生成时将默认展示此专业。</p></div></div><label>课程名称<input value="智能制造岗位项目课程" disabled/></label><label>AI课档位<select aria-label="AI课档位" value={draft.tier} onChange={event=>{setDraft(value=>normalizeConfig({...value,tier:event.target.value}));setNotice('');}}>{COURSE_TIERS.map(tier=><option key={tier}>{tier}</option>)}</select></label><div className="cms-major-summary"><span>关联专业</span><strong>{draft.major?`${draft.major.code} ${draft.major.name}`:'尚未关联专业'}</strong>{draft.tier!=='培育课'&&<button className="cms-link" onClick={()=>setActiveTab('产教模型')}>前往产教模型配置</button>}</div></section>
 {draft.tier!=='培育课'&&<section id="cms-industry" role="tabpanel" aria-labelledby="cms-industry-tab" hidden={activeTab!=='产教模型'} className="cms-panel"><div className="cms-industry-intro"><div><h2>产教模型管理</h2><p>先关联课程专业，可匹配产业链；暂无产业链数据时，可按岗位名称匹配相关岗位。</p></div><button className="primary" aria-label="选择官方专业" onClick={()=>setMajorDialog(true)}>{draft.major?'重新关联专业':'关联专业'}</button></div>
 {!draft.major?<div className="cms-empty cms-pending"><strong>待关联专业</strong><p>点击“关联专业”，选择并确认课程对应的教育部备案专业后，再匹配产业链。</p></div>:<><div className="cms-major-summary"><span>关联专业</span><strong>{draft.major.code} {draft.major.name}</strong><button className="cms-link" onClick={()=>{setDraft(changeMajor(draft,null));setNotice('');}}>清除专业关联</button></div><div className="cms-major-summary"><span>已关联产业链 {draft.chainIds.length} 条</span><strong>{chains.filter(c=>draft.chainIds.includes(c.id)).map(c=>c.name).join('、')||'请选择产业链'}</strong></div><div className="cms-match-heading"><div><h3>关联产业链</h3><p>推荐 {matches.length} 条 · 已确认 {draft.chainIds.length} 条</p></div><button className="cms-link" onClick={()=>setAll(!all)}>{all?'仅看推荐':'查看全部产业链'}</button></div><p className="cms-evidence-note">沿用专业 CMS 的匹配资料；以下推荐基于名称与规则，请核对匹配依据后勾选确认。</p>
 {!matches.length&&!draft.chainIds.length&&<JobMatching draft={draft} setDraft={setDraft}/>}
 {!shown.length&&<div className="cms-empty">暂无匹配推荐，可查看全部产业链并人工确认关联。</div>}
 <div className="cms-chain-grid">{shown.map(chain=>{const match=matches.find(c=>c.id===chain.id);return <label key={chain.id} className={`cms-chain ${draft.chainIds.includes(chain.id)?'selected':''}`}><input type="checkbox" checked={draft.chainIds.includes(chain.id)} onChange={()=>toggleChain(chain.id)}/><div><strong>{chain.name}</strong><p>{match?match.evidence.map(e=>e.evidence).join('；'):'请结合课程培养方向与岗位需求确认适用性。'}</p><small>{chain.stages.map(s=>`${s.stage} · ${s.node}`).join(' → ')}</small></div></label>;})}</div>
 {!!draft.chainIds.filter(id=>!shown.some(c=>c.id===id)).length&&<p>还有 {draft.chainIds.filter(id=>!shown.some(c=>c.id===id)).length} 条已选产业链，请在“查看全部产业链”中管理。</p>}
 </>}
 </section>}<footer className="cms-savebar"><button className="primary" onClick={()=>{const value=persist()||normalizeConfig(draft);location.href=courseHref(value);}}>保存并返回课程</button></footer></>}
 {notice&&<p className="cms-feedback" role="status">✓ {notice}</p>}{error&&<p className="form-error" role="alert">{error}</p>}
 </article></main></div>{majorDialog&&<CourseMajorDialog major={draft.major} onClose={()=>setMajorDialog(false)} onConfirm={major=>{if(!major)return;if(major.code!==draft.major?.code)setDraft(changeMajor(draft,major));setAll(false);setNotice('已关联课程专业，可配置产业链或按岗位名称匹配');setMajorDialog(false);}}/>}</div>;
}
